alpine_version = 3.17
alpine_patch_version = $(alpine_version).3
golang_buildimage=docker.io/library/golang:$(go_version)-alpine$(alpine_version)
go_version = 1.20.3
kubernetes_version=1.27.2

smoketests := \
    check-basic \
    check-hostpath \
    check-ha-controller \
    check-jointoken \
