alpine_version = 3.18
alpine_patch_version = $(alpine_version).2
golang_buildimage=docker.io/library/golang:$(go_version)-alpine$(alpine_version)
go_version = 1.25.4
kubernetes_version=1.27.2

smoketests := \
    check-basic \
    check-config-update-hcp \
    check-hostpath \
    check-pvc \
    check-ha-controller \
    check-ha-controller-etcd \
    check-ha-controller-secret \
    check-jointoken \
    check-scaling-etcd \
    check-capi-docker \
    check-capi-config-update-vm \
    check-capi-controlplane-docker \
    check-capi-controlplane-docker-downscaling \
    check-capi-controlplane-docker-worker \
    check-capi-controlplane-docker-tunneling \
    check-capi-controlplane-docker-tunneling-proxy \
    check-monitoring \
    check-capi-docker-machinedeployment \
    check-capi-docker-clusterclass \
    check-capi-docker-clusterclass-recreate-upgrade \
    check-capi-docker-clusterclass-k0smotron \
    check-capi-remote-machine \
    check-capi-remote-machine-job-provision \
    check-capi-remote-machine-template \
    check-capi-remote-machine-template-update \
    check-capi-docker-machine-change-args \
    check-capi-docker-machine-change-template \
    check-capi-docker-machine-template-update \
    check-capi-docker-machine-template-update-recreate \
    check-capi-docker-machine-template-update-recreate-kine \
    check-capi-docker-machine-template-update-recreate-single \
    check-upgrade \
