apiVersion: v1
kind: Service
metadata:
  name: {{ include "k0smotron.fullname" . }}-controller-manager-metrics-service
  namespace: k0smotron
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: k0smotron
    app.kubernetes.io/part-of: k0smotron
    control-plane: controller-manager
  {{- include "k0smotron.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    control-plane: controller-manager
    {{- include "k0smotron.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.metricsService.ports | toYaml | nindent 2 }}