apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k0smotron.fullname" . }}-controller-manager
  namespace: k0smotron
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: k0smotron
    app.kubernetes.io/part-of: k0smotron
  {{- include "k0smotron.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.controllerManager.serviceAccount.annotations | nindent 4 }}