apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k0smotron.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "k0smotron.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
