KUSTOMIZE_VERSION ?= v5.0.1
CONTROLLER_TOOLS_VERSION ?= v0.17.0
GO_VERSION ?= 1.23.2
GOLANGCILINT_VERSION ?= 1.64.0
CRDOC_VERSION ?= v0.6.2

e2esuite := \
    controlplane-remediation \
    workload-cluster-inplace-upgrade \
    workload-cluster-recreate-upgrade \
    admission-webhook-t1 \
    admission-webhook-t2 \