apiVersion: v1
kind: ConfigMap
metadata:
  name: credential-providers-config
  namespace: k0smotron
data:
  provider-config.json: |
    {
      "providers": [
        {
          "name": "kubeconfig-secretreader",
          "execConfig": {
            "apiVersion": "client.authentication.k8s.io/v1",
            "command": "/plugins/bin/kubeconfig-secretreader-plugin",
            "provideClusterInfo": true
          }
        }
      ]
    }
