---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-k0smotron-io-v1beta1-cluster
  failurePolicy: Fail
  name: mutate-k0smotron-cluster-v1beta1.k0smotron.io
  rules:
  - apiGroups:
    - k0smotron.io
    apiVersions:
    - v1beta1
    operations:
    - CREATE
    - UPDATE
    resources:
    - clusters
  sideEffects: None
