/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package k0smotronio

import (
	"context"
	"crypto/rand"
	"encoding/hex"
	"fmt"

	km "github.com/k0sproject/k0smotron/api/k0smotron.io/v1beta2"
	kcontrollerutil "github.com/k0sproject/k0smotron/internal/controller/util"
	v1 "k8s.io/api/core/v1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/util/intstr"
	"sigs.k8s.io/controller-runtime/pkg/client"
)

// natsStoreDir is the path inside the k0s container where the embedded NATS
// JetStream store is kept. A PersistentVolumeClaim is mounted here.
const natsStoreDir = "/nats-data"

// natsServerConfigPath is the path to the NATS server configuration file
// generated by the entrypoint script at pod startup.
const natsServerConfigPath = "/etc/nats/nats.conf"

// natsTokenPlaceholder is substituted with the real NATS auth token in the
// k0s config YAML at pod startup by the entrypoint script.
const natsTokenPlaceholder = "__K0SMOTRON_NATS_TOKEN__"

func (scope *kmcScope) reconcileNats(ctx context.Context, kmc *km.Cluster) error {
	if kmc.Spec.Storage.Type != km.StorageTypeNATS {
		return nil
	}
	if err := scope.reconcileNatsSvc(ctx, kmc); err != nil {
		return fmt.Errorf("error reconciling NATS service: %w", err)
	}
	return scope.reconcileNatsTokenSecret(ctx, kmc)
}

// reconcileNatsSvc ensures the headless Service used for NATS cluster routing exists.
// PublishNotReadyAddresses is set so that pod DNS entries are resolvable before pods are Ready.
func (scope *kmcScope) reconcileNatsSvc(ctx context.Context, kmc *km.Cluster) error {
	labels := kcontrollerutil.LabelsForK0smotronControlPlane(kmc)

	svc := v1.Service{
		TypeMeta: metav1.TypeMeta{
			APIVersion: "v1",
			Kind:       "Service",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:        kmc.GetNatsServiceName(),
			Namespace:   kmc.Namespace,
			Labels:      labels,
			Annotations: kcontrollerutil.AnnotationsForK0smotronCluster(kmc),
		},
		Spec: v1.ServiceSpec{
			Type:                     v1.ServiceTypeClusterIP,
			ClusterIP:                v1.ClusterIPNone,
			Selector:                 labels,
			PublishNotReadyAddresses: true,
			Ports: []v1.ServicePort{
				{
					Name:       "cluster",
					Port:       6222,
					TargetPort: intstr.FromInt32(6222),
				},
			},
		},
	}

	_ = kcontrollerutil.SetExternalOwnerReference(kmc, &svc, scope.client.Scheme(), scope.externalOwner)
	return scope.reconcileResource(ctx, kmc, &svc)
}

// reconcileNatsTokenSecret ensures the NATS auth token Secret exists.
// If the user specified tokenSecretName, the secret must already exist.
// Otherwise a new secret with a random 32-byte hex token is created (once).
func (scope *kmcScope) reconcileNatsTokenSecret(ctx context.Context, kmc *km.Cluster) error {
	secretName := kmc.GetNatsTokenSecretName()

	existing := &v1.Secret{}
	err := scope.client.Get(ctx, client.ObjectKey{Namespace: kmc.Namespace, Name: secretName}, existing)
	if err == nil {
		return nil // already exists
	}
	if !apierrors.IsNotFound(err) {
		return fmt.Errorf("failed to check NATS token secret: %w", err)
	}

	// Auto-generate a random token.
	token, err := generateNatsToken()
	if err != nil {
		return fmt.Errorf("failed to generate NATS token: %w", err)
	}

	secret := &v1.Secret{
		TypeMeta: metav1.TypeMeta{
			APIVersion: "v1",
			Kind:       "Secret",
		},
		ObjectMeta: metav1.ObjectMeta{
			Name:        secretName,
			Namespace:   kmc.Namespace,
			Labels:      kcontrollerutil.LabelsForK0smotronControlPlane(kmc),
			Annotations: kcontrollerutil.AnnotationsForK0smotronCluster(kmc),
		},
		Data: map[string][]byte{
			"token": []byte(token),
		},
	}
	_ = kcontrollerutil.SetExternalOwnerReference(kmc, secret, scope.client.Scheme(), scope.externalOwner)
	if err := scope.reconcileResource(ctx, kmc, secret); err != nil {
		if apierrors.IsAlreadyExists(err) {
			return nil
		}
		return fmt.Errorf("failed to create NATS token secret: %w", err)
	}
	return nil
}

func generateNatsToken() (string, error) {
	b := make([]byte, 32)
	if _, err := rand.Read(b); err != nil {
		return "", err
	}
	return hex.EncodeToString(b), nil
}

// natsDataSourceURL returns the kine NATS datasource URL for the given cluster.
//
// The embedded NATS server is configured via a file written by the entrypoint
// script (natsServerConfigPath), which sets the JetStream store directory,
// auth token, and cluster routing for multi-replica deployments.
//
// The auth token placeholder (natsTokenPlaceholder) in the URL is substituted
// with the real token at pod startup by the entrypoint script using the
// K0SMOTRON_NATS_TOKEN environment variable.
//
// For multi-replica clusters the replicas parameter instructs kine to use
// JetStream replication across all NATS cluster members.
func natsDataSourceURL(kmc *km.Cluster) string {
	if kmc.Spec.Replicas <= 1 {
		return fmt.Sprintf("nats://?serverConfig=%s", natsServerConfigPath)
	}
	return fmt.Sprintf("nats://?serverConfig=%s&replicas=%d",
		natsServerConfigPath, kmc.Spec.Replicas)
}
