//go:build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta2

import (
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Initialization) DeepCopyInto(out *Initialization) {
	*out = *in
	if in.ControlPlaneInitialized != nil {
		in, out := &in.ControlPlaneInitialized, &out.ControlPlaneInitialized
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Initialization.
func (in *Initialization) DeepCopy() *Initialization {
	if in == nil {
		return nil
	}
	out := new(Initialization)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K0sControlPlane) DeepCopyInto(out *K0sControlPlane) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K0sControlPlane.
func (in *K0sControlPlane) DeepCopy() *K0sControlPlane {
	if in == nil {
		return nil
	}
	out := new(K0sControlPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *K0sControlPlane) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K0sControlPlaneList) DeepCopyInto(out *K0sControlPlaneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]K0sControlPlane, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K0sControlPlaneList.
func (in *K0sControlPlaneList) DeepCopy() *K0sControlPlaneList {
	if in == nil {
		return nil
	}
	out := new(K0sControlPlaneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *K0sControlPlaneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K0sControlPlaneMachineTemplate) DeepCopyInto(out *K0sControlPlaneMachineTemplate) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K0sControlPlaneMachineTemplate.
func (in *K0sControlPlaneMachineTemplate) DeepCopy() *K0sControlPlaneMachineTemplate {
	if in == nil {
		return nil
	}
	out := new(K0sControlPlaneMachineTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K0sControlPlaneMachineTemplateSpec) DeepCopyInto(out *K0sControlPlaneMachineTemplateSpec) {
	*out = *in
	out.InfrastructureRef = in.InfrastructureRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K0sControlPlaneMachineTemplateSpec.
func (in *K0sControlPlaneMachineTemplateSpec) DeepCopy() *K0sControlPlaneMachineTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(K0sControlPlaneMachineTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K0sControlPlaneSpec) DeepCopyInto(out *K0sControlPlaneSpec) {
	*out = *in
	in.K0sConfigSpec.DeepCopyInto(&out.K0sConfigSpec)
	if in.MachineTemplate != nil {
		in, out := &in.MachineTemplate, &out.MachineTemplate
		*out = new(K0sControlPlaneMachineTemplate)
		(*in).DeepCopyInto(*out)
	}
	in.KubeconfigSecretMetadata.DeepCopyInto(&out.KubeconfigSecretMetadata)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K0sControlPlaneSpec.
func (in *K0sControlPlaneSpec) DeepCopy() *K0sControlPlaneSpec {
	if in == nil {
		return nil
	}
	out := new(K0sControlPlaneSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K0sControlPlaneStatus) DeepCopyInto(out *K0sControlPlaneStatus) {
	*out = *in
	in.Initialization.DeepCopyInto(&out.Initialization)
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.ReadyReplicas != nil {
		in, out := &in.ReadyReplicas, &out.ReadyReplicas
		*out = new(int32)
		**out = **in
	}
	if in.AvailableReplicas != nil {
		in, out := &in.AvailableReplicas, &out.AvailableReplicas
		*out = new(int32)
		**out = **in
	}
	if in.UpToDateReplicas != nil {
		in, out := &in.UpToDateReplicas, &out.UpToDateReplicas
		*out = new(int32)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K0sControlPlaneStatus.
func (in *K0sControlPlaneStatus) DeepCopy() *K0sControlPlaneStatus {
	if in == nil {
		return nil
	}
	out := new(K0sControlPlaneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K0sControlPlaneTemplate) DeepCopyInto(out *K0sControlPlaneTemplate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K0sControlPlaneTemplate.
func (in *K0sControlPlaneTemplate) DeepCopy() *K0sControlPlaneTemplate {
	if in == nil {
		return nil
	}
	out := new(K0sControlPlaneTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *K0sControlPlaneTemplate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K0sControlPlaneTemplateList) DeepCopyInto(out *K0sControlPlaneTemplateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]K0sControlPlaneTemplate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K0sControlPlaneTemplateList.
func (in *K0sControlPlaneTemplateList) DeepCopy() *K0sControlPlaneTemplateList {
	if in == nil {
		return nil
	}
	out := new(K0sControlPlaneTemplateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *K0sControlPlaneTemplateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K0sControlPlaneTemplateMachineTemplate) DeepCopyInto(out *K0sControlPlaneTemplateMachineTemplate) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K0sControlPlaneTemplateMachineTemplate.
func (in *K0sControlPlaneTemplateMachineTemplate) DeepCopy() *K0sControlPlaneTemplateMachineTemplate {
	if in == nil {
		return nil
	}
	out := new(K0sControlPlaneTemplateMachineTemplate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K0sControlPlaneTemplateMachineTemplateSpec) DeepCopyInto(out *K0sControlPlaneTemplateMachineTemplateSpec) {
	*out = *in
	if in.NodeDrainTimeout != nil {
		in, out := &in.NodeDrainTimeout, &out.NodeDrainTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.NodeVolumeDetachTimeout != nil {
		in, out := &in.NodeVolumeDetachTimeout, &out.NodeVolumeDetachTimeout
		*out = new(v1.Duration)
		**out = **in
	}
	if in.NodeDeletionTimeout != nil {
		in, out := &in.NodeDeletionTimeout, &out.NodeDeletionTimeout
		*out = new(v1.Duration)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K0sControlPlaneTemplateMachineTemplateSpec.
func (in *K0sControlPlaneTemplateMachineTemplateSpec) DeepCopy() *K0sControlPlaneTemplateMachineTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(K0sControlPlaneTemplateMachineTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K0sControlPlaneTemplateResource) DeepCopyInto(out *K0sControlPlaneTemplateResource) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K0sControlPlaneTemplateResource.
func (in *K0sControlPlaneTemplateResource) DeepCopy() *K0sControlPlaneTemplateResource {
	if in == nil {
		return nil
	}
	out := new(K0sControlPlaneTemplateResource)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K0sControlPlaneTemplateResourceSpec) DeepCopyInto(out *K0sControlPlaneTemplateResourceSpec) {
	*out = *in
	in.K0sConfigSpec.DeepCopyInto(&out.K0sConfigSpec)
	if in.MachineTemplate != nil {
		in, out := &in.MachineTemplate, &out.MachineTemplate
		*out = new(K0sControlPlaneTemplateMachineTemplate)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K0sControlPlaneTemplateResourceSpec.
func (in *K0sControlPlaneTemplateResourceSpec) DeepCopy() *K0sControlPlaneTemplateResourceSpec {
	if in == nil {
		return nil
	}
	out := new(K0sControlPlaneTemplateResourceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K0sControlPlaneTemplateSpec) DeepCopyInto(out *K0sControlPlaneTemplateSpec) {
	*out = *in
	in.Template.DeepCopyInto(&out.Template)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K0sControlPlaneTemplateSpec.
func (in *K0sControlPlaneTemplateSpec) DeepCopy() *K0sControlPlaneTemplateSpec {
	if in == nil {
		return nil
	}
	out := new(K0sControlPlaneTemplateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K0sControlPlaneValidator) DeepCopyInto(out *K0sControlPlaneValidator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K0sControlPlaneValidator.
func (in *K0sControlPlaneValidator) DeepCopy() *K0sControlPlaneValidator {
	if in == nil {
		return nil
	}
	out := new(K0sControlPlaneValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K0smotronControlPlane) DeepCopyInto(out *K0smotronControlPlane) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K0smotronControlPlane.
func (in *K0smotronControlPlane) DeepCopy() *K0smotronControlPlane {
	if in == nil {
		return nil
	}
	out := new(K0smotronControlPlane)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *K0smotronControlPlane) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K0smotronControlPlaneList) DeepCopyInto(out *K0smotronControlPlaneList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]K0smotronControlPlane, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K0smotronControlPlaneList.
func (in *K0smotronControlPlaneList) DeepCopy() *K0smotronControlPlaneList {
	if in == nil {
		return nil
	}
	out := new(K0smotronControlPlaneList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *K0smotronControlPlaneList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K0smotronControlPlaneStatus) DeepCopyInto(out *K0smotronControlPlaneStatus) {
	*out = *in
	in.Initialization.DeepCopyInto(&out.Initialization)
	if in.Replicas != nil {
		in, out := &in.Replicas, &out.Replicas
		*out = new(int32)
		**out = **in
	}
	if in.ReadyReplicas != nil {
		in, out := &in.ReadyReplicas, &out.ReadyReplicas
		*out = new(int32)
		**out = **in
	}
	if in.AvailableReplicas != nil {
		in, out := &in.AvailableReplicas, &out.AvailableReplicas
		*out = new(int32)
		**out = **in
	}
	if in.UpToDateReplicas != nil {
		in, out := &in.UpToDateReplicas, &out.UpToDateReplicas
		*out = new(int32)
		**out = **in
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]v1.Condition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K0smotronControlPlaneStatus.
func (in *K0smotronControlPlaneStatus) DeepCopy() *K0smotronControlPlaneStatus {
	if in == nil {
		return nil
	}
	out := new(K0smotronControlPlaneStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *K0smotronControlPlaneValidator) DeepCopyInto(out *K0smotronControlPlaneValidator) {
	*out = *in
	out.cv = in.cv
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new K0smotronControlPlaneValidator.
func (in *K0smotronControlPlaneValidator) DeepCopy() *K0smotronControlPlaneValidator {
	if in == nil {
		return nil
	}
	out := new(K0smotronControlPlaneValidator)
	in.DeepCopyInto(out)
	return out
}
