resources:
 - ./bases/infrastructure.cluster.x-k8s.io_pooledremotemachines.yaml
 - ./bases/infrastructure.cluster.x-k8s.io_remoteclusters.yaml
 - ./bases/infrastructure.cluster.x-k8s.io_remoteclustertemplates.yaml
 - ./bases/infrastructure.cluster.x-k8s.io_remotemachines.yaml
 - ./bases/infrastructure.cluster.x-k8s.io_remotemachinetemplates.yaml
