# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- ../../bootstrap/crd
- ../../controlplane/crd
- ../../infrastructure/crd
#+kubebuilder:scaffold:crdkustomizeresource

patches:
- path: patches/webhook_in_k0scontrolplanes.yaml
- path: patches/webhook_in_k0scontrolplanetemplates.yaml
- path: patches/webhook_in_k0smotroncontrolplanes.yaml
- path: patches/conversion_in_remotemachines.yaml
- path: patches/conversion_in_pooledremotemachines.yaml
- path: patches/webhook_conversion_in_k0smotron_cluster.yaml
- path: patches/cainjection_in_k0scontrolplanes.yaml

configurations:
- kustomizeconfig.yaml