/*
Copyright 2026.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package controlplane

import (
	"context"

	corev1 "k8s.io/api/core/v1"
	apierrors "k8s.io/apimachinery/pkg/api/errors"
	"sigs.k8s.io/cluster-api/util/secret"
	"sigs.k8s.io/controller-runtime/pkg/client"

	kcerts "github.com/k0sproject/k0smotron/v2/internal/certs"
)

// caPurposes are the certificate authorities cluster-api creates for every
// cluster. Leaf certificates on K0sControlPlane machines are generated by k0s
// on the machine itself and are not visible from the management cluster, so
// only the CAs can be reported here.
//
// secret.ServiceAccount is deliberately excluded: the "sa" secret holds a
// keypair rather than a certificate, so kcerts.Inspect cannot parse it and it
// has no expiry to report.
var caPurposes = []secret.Purpose{
	secret.ClusterCA,
	secret.EtcdCA,
	secret.FrontProxyCA,
}

// inspectClusterCertificates reads every CA secret belonging to a cluster.
// A missing secret is not an error — it simply has nothing to report yet. A
// secret that exists but cannot be parsed is returned in the second result so
// the caller reports it as Unknown rather than assuming it is healthy.
func inspectClusterCertificates(ctx context.Context, c client.Client, key client.ObjectKey) ([]kcerts.Info, []string) {
	var (
		infos      []kcerts.Info
		unreadable []string
	)

	for _, purpose := range caPurposes {
		s := &corev1.Secret{}
		name := client.ObjectKey{Namespace: key.Namespace, Name: secret.Name(key.Name, purpose)}

		if err := c.Get(ctx, name, s); err != nil {
			if !apierrors.IsNotFound(err) {
				unreadable = append(unreadable, string(purpose))
			}
			continue
		}

		// The purpose label carries the fixed cluster-api purpose string
		// rather than the secret name, which a user may have influenced and
		// which would otherwise leak into report.Emit's metric labels.
		if s.Labels == nil {
			s.Labels = map[string]string{}
		}
		s.Labels[kcerts.PurposeLabel] = string(purpose)

		got, err := kcerts.Inspect(s)
		if err != nil {
			unreadable = append(unreadable, string(purpose))
			continue
		}

		infos = append(infos, got...)
	}

	return infos, unreadable
}
