apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
  namespace: k0smotron
spec:
  template:
    spec:
      containers:
      - name: manager
        args:
        - "--health-probe-bind-address=:8081"
        - "--metrics-bind-address=127.0.0.1:8080"
        - "--leader-elect"
        - "--enable-controller=standalone"