name: Build docs

on:
  pull_request:
    branches:
      - main
      - release-*
    paths:
      - mkdocs.yml
      - docs/**

jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout k0smotron
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Set up Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: pip
          cache-dependency-path: docs/requirements.txt
      - name: Install dependencies
        run: |
          # https://github.com/actions/setup-python/issues/521
          # https://github.com/actions/python-versions/blob/3.10.9-3636985951/installers/nix-setup-template.sh#L53
          pip install --disable-pip-version-check -r docs/requirements_pip.txt
          pip --version
          pip install --disable-pip-version-check -r docs/requirements.txt

      - name: Generate docs
        run: make -C docs docs

  dev-container:
      name: Build docs dev container
      runs-on: ubuntu-latest
      steps:
        - name: Checkout k0s
          uses: actions/checkout@v5

        - name: Build docs dev container
          run: make -C docs .docker-image.serve-dev.stamp
