name: E2E tests

on:
  workflow_call:
    inputs:
      test-name:
        required: true
        type: string
      flavor:
        required: false
        type: string

jobs:
  e2e:
    name: "${{ inputs.test-name }} :: ${{ inputs.flavor }}"
    runs-on: oracle-vm-16cpu-64gb-x86-64
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version-file: go.mod

      - name: Download image bundle
        uses: actions/download-artifact@v5
        with:
          name: k0smotron-image-bundle

      - name: Load k0smotron image bundle
        run: |
          docker load -i k0smotron-image-bundle.tar

      - name: Run e2e test
        run: |
          make e2e TEST_NAME="${{ inputs.test-name }}" FLAVOR="${{ inputs.flavor }}"

      - name: Archive artifacts
        if: failure()
        uses: actions/upload-artifact@v4.3.2
        with:
          name: e2e-artifacts
          path: _artifacts
          if-no-files-found: ignore